version: '2.1'
orbs:
  terraform: circleci/terraform@3.1
jobs:
  deploy-app:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: ./terraform/k8s
      - terraform/validate:
          path: ./terraform/k8s
      - terraform/fmt:
          path: ./terraform/k8s
      - terraform/plan:
          path: ./terraform/k8s
      - terraform/apply:
          path: ./terraform/k8s
      # - run:
      #     name: Failure
      #     command: "failed_notification_step"
      #     when: on_fail
      # - terraform/destroy:
      #     path: ./terraform/docker
  destroy-app:
    executor: terraform/default
    steps:
      - checkout
      - terraform/destroy:
          path: ./terraform/docker
    working_directory: ~/src
workflows:
  deploy-app:
    jobs:
      - deploy-app
      - destroy-app:
        type: approval 
          requires:
            - deploy-app
