version: '2.1'
orbs:
  terraform: circleci/terraform@3.1
jobs:
  deploy-app:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: ./terraform/docker
      - terraform/validate:
          path: ./terraform/docker
      - hold:
         type: approval
      - terraform/fmt:
          path: ./terraform/docker
      - terraform/plan:
          path: ./terraform/docker
      - terraform/apply:
          path: ./terraform/docker
      - terraform/destroy:
          path: ./terraform/docker
    working_directory: ~/src

  # destroy-app:
  #   executor: terraform/default
  #   steps:
  #     - checkout
  #     - terraform/destroy:
  #         path: ./terraform/docker
  #   working_directory: ~/src
workflows:
  deploy-app:
    jobs:
      - deploy-app
      # - hold:
      #     type: approval 
      #     requires:
      #         - deploy-app
      # - destroy-app:
      #     requires:
      #         - hold
