version: 2.1
orbs:
    aws-s3: circleci/aws-s3@3.0
jobs:
    build:
      docker:
        - image: cimg/node:15.0.1-browsers
      working_directory: ~/repo
      steps:
        - checkout
        - run: cd client2 && npm install
        - run: cd client2 && npm run build
    deploy:
      docker:
      - image: 'cimg/python:3.6'
      steps:
        - checkout
        - aws-s3/sync:
            arguments: |
              --acl public-read \
              --cache-control "max-age=86400"
            aws-access-key-id: AWS_ACCESS_KEY_ID
            aws-region: AWS_REGION
            aws-secret-access-key: AWS_SECRET_ACCESS_KEY
            from: client2/build
            to: 's3://s3-github-actions-rexben/'

workflows:
  deploy-app:
    jobs:
      - build
      - deploy