version: 2.1
jobs:
    build:
      docker:
        - image: cimg/node:15.0.1-browsers
      working_directory: ~/repo
      steps:
        - checkout
        - run: cd client2 && npm install
        - run: cd client2 && npm run build
        - run: sudo apt-get update && sudo apt-get install python3.7
        - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
        - run: sudo python3.7 get-pip.py
        - run: sudo python3.7 -m pip install --upgrade pip setuptools wheel
        - run: sudo python3.7 -m pip install pipenv
        - run: sudo pip install awscli --upgrade
        - run: aws --version
        - run: aws s3 ls
        - run: aws s3 sync client2/build/ s3://s3-github-actions-rexben --delete
