version: '2.1'
orbs:
  terraform: circleci/terraform@3.1
  aws-ecr: circleci/aws-ecr@0.0.4

jobs:
  - aws-ecr/build-and-push-image:
      account-url: AWS_ECR_ACCOUNT_URL
      aws-access-key-id: AWS_ACCESS_KEY_ID
      aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      create-repo: true
      dockerfile: Dockerfile
      path: ./server2
      region: AWS_REGION
      repo: myECRRepository
      tag: latest
      platform: linux/amd64
  - single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: ./terraform/docker
      - terraform/validate:
          path: ./terraform/docker
      - terraform/fmt:
          path: ./terraform/docker
      - terraform/plan:
          path: ./terraform/docker
      - terraform/apply:
          path: ./terraform/docker
      # - terraform/destroy:
      #     path: ./terraform/docker
    working_directory: ~/src

workflows:
    build_and_push_image:
      jobs:
        - aws-ecr/build-and-push-image
        # - single-job-lifecycle:
        #   requires:
        #     - aws-ecr/build-and-push-image
