version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
jobs:
    build:
      docker:
        - image: cimg/node:15.0.1-browsers
      working_directory: ~/repo
      steps:
        - checkout
        - run: cd client2 && npm install
        - run: cd client2 && npm run build
  
        - aws-s3/sync:
            from: client2/build
            to: "s3://s3-github-actions-rexben/"
            arguments: |
              --acl public-read \
              --cache-control "max-age=86400"                
            overwrite: true